### ISSUE TITLE
How to use QuickUMLS with full UMLS installation?

### ISSUE THREAD

**Issue by sudarshan85** [medspacy/medspacy#115]
Hi,

I'm starting with Medspacy and I have a question about using it with QuickUMLS. I've obtained the UMLS license and installed full UMLS on my computer. I've also installed QuickUMLS and created its own "UMLS installation". I'm following the [11-QuickUMLS_Extraction](https://nbviewer.org/github/medspacy/medspacy/blob/master/notebooks/11-QuickUMLS_Extraction.ipynb) and I'd like to know how to use the full QuickUMLS installation that I have on my computer instead of just the small sample provided in the notebook. 

I am assuming I can create a pipeline component with the QuickUMLS path but I'm not able to find the code to do that.

Thanks.

**Comment by burgersmoke** [comment]
Hello @sudarshan85.  After downloading a UMLS distribution, there is still the step of running code to convert desired subsets of it into a QuickUMLS database.  This is what allows the underlying approximate matching (simstring) to be so fast.  

The original authors of QuickUMLS have written an explanation about how to do this.  I've updated some of this documentation myself since I've been involved.  Can you please review this and then open a new ticket here if you have any specific questions?

 You basically need to look at the 3rd bullet here on installation.  When you look at the arguments passed in to the QuickUMLS database conversion, you will see that there are some important decisions to make as far as database format (I would use the new default), whether your concepts should preserve case or be case insensitive, how to handle unicode, etc.  These decisions (as well as the need for a UMLS license) are some of the reasons that this is a separate step:
 
 https://github.com/Georgetown-IR-Lab/QuickUMLS

**Comment by burgersmoke** [comment]
And yes, once you've created your own QuickUMLS database of all the concepts you want, you will want to pass in the path to this location to the QuickUMLS component in the component config.

**Comment by sudarshan85** [comment]
Hello,

Thank you for your very quick reply! Apologies for not being clear in my questions. I've actually done the QuickUMLS database part and have the path where these files are stored. I've run through the `matcher` example QuickUMLS folks have given in their github repo and it works.

What I don't know how to do is how to pass in the QuickUMLS database into medspacy. I didn't find any example on the notebook to do that. 

Specifically, from the QuickUMLS repo:
```
from quickumls.spacy_component import SpacyQuickUMLS

nlp = spacy.load('en_core_web_sm')
quickumls_component = SpacyQuickUMLS(nlp, 'PATH_TO_QUICKUMLS_DATA')
nlp.add_pipe(quickumls_component)
```
Do I just replace `spacy` here with `medspacy`?

**Comment by burgersmoke** [comment]
Ah, I understand where you are now.  Let me get back to you in a moment to make sure that what you're asking is possible with our most recent `medspacy` release.  I assume you are using medspacy `0.2.0.0`.  Is that right?

**Comment by sudarshan85** [comment]
> I assume you are using medspacy `0.2.0.0`. Is that right?

Yes that is correct.

**Comment by sudarshan85** [comment]
Hey @burgersmoke Were you able to find out if this is possible?

**Comment by burgersmoke** [comment]
@sudarshan85 I apologize that it took me so long to get back to this issue.  I was fairly certain that the current medspacy release would allow this and it worked perfectly for me.

There are two different ways you can do this:

- Use the `medspacy.load()` helper function.  You can pass in an optional parameter `quickumls_path` which will pass the path of your QuickUMLS resources to the QuickUMLS spacy component when it initializes.  Make sure to enable the 'medspacy_quickumls' component as well.  Note that this may not be enabled on Windows by default due to challenging dependencies with pip.  I've provided some sample code of this below.
- Instead of using `medspacy.load()` as a helper function, you can set up your own pipeline manually without the helper utility.  Line 111 of `util.py` does this:
`nlp.add_pipe("medspacy_quickumls", config={"quickumls_path": quickumls_path})`

So here is the sample code I used to set up a minimal example to show how to do this.  Note that my own QuickUMLS resources were a small subset of UMLS (i.e. RxNorm only).  You'll need to change this to the path where you have your resources.  

Note, when I run this code, I do get expected RxNorm extractions for these medications.  This is the output I get:

```
Total entities found: 2
153165
lipitor
224920
synthroid
```

Can you tell me if this works for you?

```import spacy
import medspacy

print('DONE with imports')

QUICKUMLS_PATH = r'E:\temp_quickumls\rxnorm'

print(QUICKUMLS_PATH)

nlp = medspacy.load(quickumls_path = QUICKUMLS_PATH,
                   enable = ['medspacy_quickumls']
                   )

print(nlp.pipe_names)

text = 'Pt has been taking lipitor for 10 years, but started synthroid this week'

doc = nlp(text)

print('Total entities found: {}'.format(len(doc.ents)))

for ent in doc.ents:
    print(ent.label_)
    print(ent.text)
```

**Comment by burgersmoke** [comment]
I have not heard anything back, so I will close this issue since sample code and explanations are available above.  Please let us know if there are additional questions.

**Comment by sudarshan85** [comment]
Thank you. I'll try this out and report back when I get a chance.

**Comment by burgersmoke** [comment]
Excellent.  I wish you good luck and a very happy clinical concept extraction!
