### ISSUE TITLE
Use of pretrained Scispacy models?

### ISSUE THREAD

**Issue by mkeywood1** [medspacy/medspacy#131]
Hi,

Is it possible to use the pretrained SciSpacy models with MedSpacy?
I use the BC5CDR trained model (https://s3-us-west-2.amazonaws.com/ai2-s2-scispacy/releases/v0.5.0/en_ner_bc5cdr_md-0.5.0.tar.gz) in spacy fine, but want to use it in MedSpacy.

When I follow the guidance in your training notebook `06-Using-Pretrained-Models.ipynb` and replace the model with this one `nlp = medspacy.load("en_ner_bc5cdr_md")` it loads it fine. 
`nlp.get_pipe("ner").labels` shows me what I would expect, ie the DISEASE and CHEMICAL labels, but when I try and use it with `doc = nlp(text)` it errors with `ValueError: [E043] Refusing to write to token.sent_start if its document is parsed, because this may cause inconsistent state.`

Googling that shows it fixed by either doing `nlp.add_pipe("sentencizer", first = True)` or `nlp.add_pipe("sentencizer", before="parser")` but neither of them make a difference and I get the same errors.

Has anyone successfully used  SciSpacy models with MedSpacy, and if so can you point me in the right direction please?

**Comment by mkeywood1** [comment]
OK it looks like it's a problem if I include `pyrush`.

If I just load with `nlp = medspacy.load('en_ner_bc5cdr_md', enable=['sentencizer', 'tagger', 'parser', 'ner', 'target_matcher', 'context', 'sectionizer'])` it works fine. But if I include `pyrush` I get that error.

Any ideas?
Thanks :)

**Comment by MichalMalyska** [comment]
> 

**I think** this is because the "en_ner_bc5cdr_md" already contains a sentence splitting component (I think parser does it by default, but you have included 'sentencizer' which seems to imply there is a specific one) so if you add the pyrush in the pipeline it gets added on top of the sentencizer which results in the error above (you have a sentencizer AND pyrush clashing)

**Comment by burgersmoke** [comment]
I agree with @MichalMalyska that the existing sentence boundary detection component in scispacy conflicts with pyrush.  Since only one sentence method is allowed at a time, either scispacy or pyrush should be used.

@mkeywood1 Can you try to load scispacy, remove its sentencizer, and then add pyrush (in the same place in the pipeline) and see how this behaves.  If you still believe there is an issue with this, could you re-open this ticket?
