### ISSUE TITLE
QuickUMLS: lookups now fail for multi word sequences with leveldb but unqlite works as expected

### ISSUE THREAD

**Issue by burgersmoke** [medspacy/medspacy#141]
@turbosheep recently identified that using leveldb, multi-word lookups do not work in QuickUMLS as expected.  There has not been much development or maintenance on the Python wrapper of leveldb, so it might be time to move away from this in our own fork of QuickUMLS.

**Comment by RonWilkinson** [comment]
I am running MedSpacy on Windows with quickUMLS installed using unqlite.  

Here is an example of a multiword sequence that is not flagged by quickUMLS as I would have expected.  The phrase "Moderate persistent asthma" is flagged as three separate terms:
![image](https://user-images.githubusercontent.com/11411901/189155068-b29cfe07-7eb5-4fd0-8012-5d19383f946c.png).
I would have liked the whole phrase to be detected as the single concept "Moderate persistent asthma C1960047". 

It does not seem to matter how I adjust the quickUMLS parameters overlapping_criteria, similarity_name, and threshold, which I thought might be relevant.

The way I adjust the parameters despite no explicit support in the medspacy_quickumls wrapper is with code like this, varying the parameter values:

![image](https://user-images.githubusercontent.com/11411901/189173885-c397844b-4521-4c2d-8d11-68d4316537d3.png)
![image](https://user-images.githubusercontent.com/11411901/189173338-38c72ffa-8d0b-4555-8d06-3521f74eb7a7.png)

I know the parameters are being passed into quickUMLS this way, because I have used this approach before to successfully adjust the threshold parameter alone for other purposes.
