### ISSUE TITLE
module 'medspacy' has no attribute 'load'

### ISSUE THREAD

**Issue by pssllp** [medspacy/medspacy#169]
I installed medspacy using the setup.py on windows. But I can't use the load() attribute. It throws an error

**Comment by burgersmoke** [comment]
Could you share more about the error?  I am curious since all of our continuous integration is running and uses this function without issue (see https://github.com/medspacy/medspacy/actions).

A few questions:

- Can you share the callstack of the error?
- Can you share the code you are running which reproduces this?
- Were there any errors or failures when running setup.py?
- Which medspacy and Python versions are you using?

**Comment by anshupolestar** [comment]
I am getting the error while using `medspacy.load()`. 
The error message I got  is `AttributeError: module 'medspacy' has no attribute 'load'`

I modified the get_version() function of the setup.py file. Instead of getting the version from _version.py file I returned the value of the version. 
<img width="145" alt="image" src="https://user-images.githubusercontent.com/107473845/199961719-b991e45d-9dcd-460b-a89d-de2ec7d38c49.png">
I am using python 3.8.13 and medspacy 1.0.0

**Comment by burgersmoke** [comment]
@pssllp  Sorry I have not communicated with you about this in several months.  Since this comment above, a medspacy 1.0.1 was released to address Windows issues.

Could you try this again with medspacy >= 1.0.1 and let us know if you are still having issues?

I see that our continuous integration is running successfully for medspacy 1.0.1 and multiple versions of Python.

**Comment by pssllp** [comment]
Hello @burgersmoke medspacy 1.0.1 is working fine... Thanks !!!

**Comment by burgersmoke** [comment]
Great news @pssllp !  Thank you for the update.
