### ISSUE TITLE
delete or modify existing contex rules

### ISSUE THREAD

**Issue by celalp** [medspacy/medspacy#190]
Hi I need to modify some of the existing context rule (change max_scope) etc. Is there a way to do this? Do I need to create a blank a new ConText and add my rules one by one?

Thanks

**Comment by turbosheep** [comment]
Probably the best way to go about things like this would be to copy the provided context rule json into your project and make modifications to this file locally.

[https://github.com/medspacy/medspacy/blob/master/resources/context_rules.json](https://github.com/medspacy/medspacy/blob/master/resources/context_rules.json)

Then, when creating the context component in your pipeline add `"rules"` to your config dictionary.

```python
nlp.add_pipe("medspacy_context", config={"rules":"path/to/your/context_rules.json", ...  })
```

ContextRules themselves should not be modified individually because the underlying spaCy Matchers that run the rules do not allow rule modification after creation. 

This is definitely an area our documentation is missing and we are planning to do another documentation pass in the near future to add more explanations for dealing with issues like this.

**Comment by celalp** [comment]
Thanks, that's what I ended up doing anyways.
