### ISSUE TITLE
Utility function to convert doc entities to dataframe

### ISSUE THREAD

**Issue by abchapman93** [medspacy/medspacy#22]
This function would take a list of docs and return a pandas DataFrame where each row is an entity and columns contain attributes.

**Comment by turbosheep** [comment]
Partially in progress with doc_consumer in medspacy_io, but with merging certain repositories in, transforming documents into writable tables will be useful.

I was intending to also make this a pipeline component, so that each document will be processed into the specified rows and the rows can be retrieved when wishing to write to some format.

Ultimately something like...
```python
nlp = [other components, ... , doc_consumer]

docs = nlp.pipe(texts)

for doc in docs:
  data = doc.rows
  data.to_sql()
```

Pandas might be a convenient option, but i also remember running into extreme bottlenecks using the pandas.to_sql() method, even with the new "multi" option. Performance might still be an issue here worth discussing.

**Comment by abchapman93** [comment]
Agreed about the bottleneck in pandas.to_sql(). I think we might want to have a to_pandas() function separate from sql writing, I think that will be useful outside of actual I/O.

**Comment by turbosheep** [comment]
As an update:

doc_consumer.py is now in the medspacy/io/ folder in the medspacy_io branch. It has some tests, but no documentation or comments yet.

The behavior is as follows, assuming other configurations for targets, etc.
```python
consumer = DocConsumer(nlp)
doc = nlp("Pt has no cough")
doc._.get_data("ent")
>>> {"text": ["cough"], "label_": ["PROBLEM"], "start_char": [10], "end_char": [15]}

consumer = DocConsumer(nlp, context = True)
doc = nlp("Pt has no cough")
doc._.get_data("ent")
>>> {"text": ["cough"], "label_": ["PROBLEM"], "start_char": [10], "end_char": [15], "is_family": [False], "is_negated": [True], ...}

consumer = DocConsumer(nlp, sectionizer = True)
doc = nlp("Section 1: Pt has no cough")
doc._.get_data("ent")
>>> {"text": ["cough"], "label_": ["PROBLEM"], "start_char": [10], "end_char": [15], "section_title": ["section_1"], "section_parent": [None]}
```
This format is able to be directly input into a pandas dataframe for viz or further data manipulation.

You can also specify to output section spans themselves with title start/end char, span start/end char, etc.

There is also a configurable database reader/writer/pipeline factory using this doc_consumer in medspacy/io/ as well, but those features might warrant their own repository, since only the DocConsumer is a spaCy component and the readers/writers are somewhat extraneous to the core package. These can be moved later.

**Comment by abchapman93** [comment]
Before I close this old ticket out, I'll note that we now have a helper function for exactly this: `doc._.to_dataframe()`
