### ISSUE TITLE
Disambiguated spans

### ISSUE THREAD

**Issue by ssamine** [medspacy/medspacy#252]
many disease spans have been trained with words trained after a fullstop.
"The patient has metastatic adenocarcinoma"
Output: ()

"The patient has metastatic adenocarcinoma."
Output: (adenocarcinoma,)

"The patient has: Metastatic adenocarcinoma."
Output: (Metastatic adenocarcinoma,)

**Comment by burgersmoke** [comment]
Hello @ssamine,

I'm not sure if I understand what you are reporting here, so I'll try to ask a few questions here to try to comprehend what you are setting up and what you expect:

1. Medspacy doesn't release any modules out-of-the-box which would extract disease spans like the "Metastatic adenocarcinoma" that I see in this example.  Are you using some other library or knowledge base?  Perhaps scispacy?  Or your own QuickUMLS resource you built?  Or something else?
2. Can you describe your pipeline a bit more as far as the components in its configuration?
3. Are you using the default medspacy tokenizer or a different one?

Hopefully we can figure out how to best help with some additional information.

**Comment by ssamine** [comment]
1. Apologies, yes, I loaded scispacy models for this test.
2. Yes, they are basic ones ner, medspacy_sectionizer, added entity ruler, I have trouble with medspacy_pyrush (owing to my data)
3. Yes, I am using base tokenizer en_core_web_sm

**Comment by burgersmoke** [comment]
Thank you @ssamine.  This helps to understand.

This does not seem like a medspacy issue since you're using a scispacy model for the concept extraction and using a non-medspacy tokenizer.  I would be willing to bet that this behavior would be reproduced without using anything from medspacy at all.

I would suggest looking for similar reported issues or perhaps related documentation in scispacy.  If you are unable to find something, maybe you could open an issue with scispacy?  If we knew more about their concept extraction implementation, we might be able to help, but we do not want to lead you incorrectly.
