### ISSUE TITLE
Medspacy-ing in another language

### ISSUE THREAD

**Issue by mpasternak** [medspacy/medspacy#264]
Hi, 

how would you, the developers of medspacy like to see medspacy supporting other, non-English languages? 

Should I rather fork the whole project or try to support current resources in translated manner? 

For example, the whole resources directory could be moved to resources/en/ and then resources/pl/ could be added. 

But on the other hand, having 2 different test suites for 2 different languages in the same codebase... 

And if so, installing the single package with all those other languages that I don't plan to use... doesn't seem like a good idea. 

So perhaps I rather create a thin wrapper over medspacy, using its original names for categories, sections, etc.. but I will translate header names. And create separate test suite for another language. 

Just sharing some thoughts, it's not exactly an issue per-se. But perhaps there's something in the docs that somebody could point me to or perhaps you did gave this topic some thoughts. 

The more I think about it, the more I think that I'll create a thin wrapper with my national language data over medspacy.

**Comment by burgersmoke** [comment]
@mpasternak We are very interested in supporting medspacy for other languages.  I've been planning on some work on this for a number of weeks and I'll be moving forward on it now.

The ideas you are proposing of having resource folders per language (e.g., resources/en/,  resources/pl/, resources/es/) is exactly what I will be doing.

`medspacy.load()` will also get a default language parameter of `en` but can be changed to other languages.  More to come on that.

Also, following how spacy does this, there will be additional tests added under  `/tests/lang` by ISO code, so there may be a `/tests/lang/pl`, etc.

More to come, but once I start my branch, I will post the link to it here in case anyone wants to peek at it or make comments before it goes into the `develop` branch.

**Comment by burgersmoke** [comment]
FYI for anyone interested.  I'm making progress on this in a feature branch.  Currently all English tests pass again.

I'm next working on ensuring some minimal functionality in a few other languages and I will be adding tests for these as I proceed.

**Comment by mpasternak** [comment]
Really glad to hear this. 

Could we keep this issue open and close it when the internationalized branch is merged? 

Do you need any help with this task?

**Comment by burgersmoke** [comment]
> Really glad to hear this.
> 
> Could we keep this issue open and close it when the internationalized branch is merged?
> 
> Do you need any help with this task?

Yes, I will keep this open until this branch is merged in and we can continue working on other languages.

Speaking of languages, each will have its own maturity level which I will summarize in a table in the `README.md`.

That said, the most mature right now is French since there are ConText rules for it and I was able to set up just two total section rules to show proof of concept.

As far as other languages, the areas where they are lacking are due to a lack of content/rules.   For example, I thought that there was a GitHub issue where someone had posted ConText rules for Spanish, but this was not the case so I'm not sure what we might do for Spanish at this point.

Can I ask you the following?

- Is there a language in particular which you are targeting?  Is it Polish based on your examples above?
- Do you have any rules (e.g., ConText, sections, etc) which you've developed for any language?

**Comment by burgersmoke** [comment]
Medspacy 1.2.0 now supports separating and loading resources by language.  This is now released so I will close this issue.

Meanwhile, the questions and solicitation for more non-English rules still remains.  We would benefit from integrating more rules in any language, especially ConText and section rules.
