### ISSUE TITLE
Typo in pyproject.toml

### ISSUE THREAD

**Issue by ryleyb** [medspacy/medspacy#281]
https://github.com/medspacy/medspacy/blob/9d422d1ed418882e8a515ea4d461f472b989210d/pyproject.toml#L19

Should be `requirements`

**Comment by burgersmoke** [comment]
@jianlins  It seems like we should take this change, right?  Otherwise, it seems to me that this line does not do anything (i.e., does not bring in the requirements from requirements.txt.

Do you agree?  Also, do you think this could explain any build related issues we've had since we started using the .toml file?

**Comment by jianlins** [comment]
It's done with the last pull.
