### ISSUE TITLE
Can't run spacy efficiently with sectionizer turned on

### ISSUE THREAD

**Issue by MichalMalyska** [medspacy/medspacy#34]
Adding the sectionizer to a pipeline makes it non-picklable, which prevents us from using multiprocessing / n_process argument.

`import spacy
from medspacy.section_detection import Sectionizer

nlp = spacy.load("en")
sect = Sectionizer(nlp, patterns="path_to_patterns")
nlp.add_pipe(sect)

for x in nlp.pipe(["this is text 1", "this is text 2"], n_process=2):
    print(x)

PicklingError: Can't pickle <function <lambda> at 0x7f9337addb80>: attribute lookup <lambda> on medspacy.section_detection.sectionizer failed`

**Comment by turbosheep** [comment]
Hi, thanks for reporting this. I had also run into pickling errors when deploying this for our own projects. As a temporary workaround if your deployment is crucial, I have deployed multiple instances of the pipeline where `n_process=1`.

Otherwise, we are making a new release of medspacy in the next few days that we hope resolves this for future deployments.

**Comment by abchapman93** [comment]
After looking at this a little more closely, we think this will be a little more effort to implement, and will also apply to other components. I think it has to do with [spaCy's serialization methods](https://spacy.io/usage/saving-loading#serialization-methods), which we haven't implemented yet for our pipeline components.

I'm going to close this ticket and move over to #36 so that this applies to all components, not just the Sectionizer. Thank you for reporting this! This is an important improvement to make.
