### ISSUE TITLE
Not clear how to migrate from from clinical_sectionizer

### ISSUE THREAD

**Issue by nlorenzen1** [medspacy/medspacy#45]
Hi,

We currently use from clinical_sectionizer to parse sections from clinical documents. I'd like to migrate to medspacy, but it's not clear from the documentation or test (which are commented out) how to do that. 

I currently have this in my code:

from clinical_sectionizer import TextSectionizer
self.textSectionizer=TextSectionizer()
self.textSectionizer.add(patterns=self.new_patterns)

What's the equivalent in medspacy? Thanks for the help!

**Comment by turbosheep** [comment]
Hi,

Documentation and improved testing is our next priority, so we hope to improve that over time, especially since we have been getting lots of new users. Thank you for reaching out for help in the meantime, though.

The TextSectionizer was originally developed as a standalone item comparable to medspacy's Sectionizer. However, as development has continued on medspacy, not all of the features we have added to the Sectionizer are possible without the spacy dependency and development has stopped on the TextSectionizer. For now, it is not actively being developed/tested and may be deprecated and removed from medspacy (or into a standalone repository) in the future.

As for converting a TextSectionizer to the medspacy Sectionizer, the API is mostly the same.

```python
import spacy
from medspacy.section_detection import Sectionizer

nlp = spacy.load("en_core_web_sm")

sectionizer = Sectionizer(nlp, patterns=new_patterns)
```
We have recently made a change the underlying code of a lot of the matcher-based medspacy components to unify them. The `new_patterns` variable should now be a path to a JSON instead of a JSONL file or a list of `SectionRule` objects. The format of the JSON file can be seen in the default rules loaded by the sectionizer [here](https://github.com/medspacy/medspacy/blob/master/resources/section_patterns.json). The definition of a `SectionRule` is [here](https://github.com/medspacy/medspacy/blob/master/medspacy/section_detection/section_rule.py) and can be read from a JSON or a `dict`. 

From there, you can use the sectionizer in two ways. First, by using it after adding it to the spacy pipeline: 
```python
nlp.add_pipe(sectionizer)
nlp("Section 1: your text here")
```
Or by calling it on docs already processed by spaCy
```python
doc = nlp("Section 1: your text here")
doc = sectionizer(doc)
```
Then, the sections will be available in `doc._.sections` and are of the new `Section` class, which has a variety of properties, such as span of the section title or body and the label.

We have notebooks that ideally show some of the basic use cases for creating and modifying medspacy's sectionizer [here](https://github.com/medspacy/medspacy/tree/master/notebooks/section_detection), too.

I hope this helps and please feel free to follow up with more questions.
