### ISSUE TITLE
Missing negation pattern

### ISSUE THREAD

**Issue by MichalMalyska** [medspacy/medspacy#52]
I noticed that there isn't a negation pattern that is simply:

"no" 

(going forward)

I'm wondering if this is intentional or just an oversight?

**Comment by abchapman93** [comment]
Well, there is actually one which will match just "no". This is rule is on lines 654-669 of [context_rules.json](https://github.com/medspacy/medspacy/blob/master/resources/context_rules.json), and since the adjectives "abnormal" and "new" can occur 0 or 1 times ("OP": "?"), it will match just the phrase "no". 

I think when we put the ConText rules in we probably merged some rules like this which were subsets of one another, although it doesn't hurt to keep them separate either.

```json
{
      "category": "NEGATED_EXISTENCE",
      "literal": "no",
      "pattern": [
        {
          "LOWER": "no"
        },
        {
          "LOWER": {
            "IN": ["abnormal", "new"]
          },
          "OP": "?"
        }
      ],
      "direction": "FORWARD"
}
```
