### ISSUE TITLE
Problem displaying "similarity" attribute from QuickUMLS in DocConsumer

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#68]
DocConsumer for some reason does not display the "similarity" attribute correctly when added to the ent attributes.  The attached screen shot shows a doc from which I can print the QuickUMLS attributes directly, but when run through DocConsumer, all the attributes except "similarity" print correctly.  The error suggests an expectation that "similarity" is a function instead of the float that the attribute is in actuality.

![image](https://user-images.githubusercontent.com/11411901/119242936-4d061280-bb30-11eb-9149-2df2b553ff4c.png)

**Comment by abchapman93** [comment]
I think the reason for this is that the way the DocConsumer works is it first checks if there is a native spaCy attribute with the specified name, and if there isn't it looks for a custom attribute. In this case, `ent.similarity` is already defined by spaCy as a method, so that's what the DocConsumer grabs and puts here. 

I think the simplest solution would be to give your attribute a different name which is distinct from spaCy's native attributes, something like `ent._.span_similarity`

**Comment by turbosheep** [comment]
@abchapman93 I believe this similarity is a part of QuickUMLS. It’s the similarity of the match compared to the text of the CUI. So it was an oversight on our part to not rename the attribute when we updated/added QuickUMLS

**Comment by abchapman93** [comment]
Ah, I see. Well since QuickUMLS is kind of a third-party library, I still think the simplest solution would be to register a new attribute that just returns this value, something like:
`from spacy.tokens import Span; Span.set_extension("quickumls_similarity", getter=lambda x:x._.similarity)`
