### ISSUE TITLE
Want to use the section a span is in as part of tagger match.

### ISSUE THREAD

**Issue by RonWilkinson** [medspacy/medspacy#69]
I want to check for medication dosage frequency abbreviations only in the medications section of my document. The Matcher rules in Spacy say I can use syntax like: 
   `    TargetRule("Dose Frequency Abbrev.", "DOSE_FREQUENCY", pattern=[{"TEXT": {"IN":["BID","PR","PRN","TOP","QID"],
                                                             "_":{"section.category":"medications"}}}]),
`

The syntax  for using the "_" keyword in matches as described in the Spacy documenttion is:
![image](https://user-images.githubusercontent.com/11411901/119409911-017d7100-bcb6-11eb-8259-ec67a84a5627.png)

However, even with  the Sectionizer in the pipeline and my confirming that manually entering for example: doc.ents[10]._.section.category displays the section category correctly, adding in  the target rule produces the error:

> AttributeError: [E046] Can't retrieve unregistered extension attribute 'section.category'. Did you forget to call the `set_extension` method?

I think the problem is that "section" is the registered extended attribute, and its value is a section object that has the property "category", so "section.category" itself is not a recognized extended attribute.  Am I right?  If so, is there a way I can access this section property in a match rule?  Would it require a callback function or just some fancy syntax in the rule?

**Comment by abchapman93** [comment]
I see what you're trying to do, and I don't think you can do something like this in the matching syntax.

But luckily, we've also added an actual "section_category" attribute for token, so I think you should be able to just do `{"_": {"section_category": "medications"}}`. Could you try that and let me know if it works?

**Comment by turbosheep** [comment]
@abchapman93 just finished typing ahead of me and I think his answer was effectively the same as mine, but to elaborate just a little bit...

This error is occurring because `section.category` is not an attribute by itself. `ent._.section` returns a custom `Section` object, which has the attribute `category`. The `getattr` method called under the hood in the TargetMatcher looks directly at the Span for the attribute with the name `section.category` and does not do any searching for sub-attributes. 

However, since we store a lot of important information in `Section`, we have registered all of the attributes spaCy attributes with names like `section_category` that accesses `Section.category` at the Token and Span levels.

Our example notebooks have not kept up with showing our additions to the extensions registered by our components, but we have all the extensions registered in one file here. This should show a complete list of the attributes available at all levels for the components included in this repository.

https://github.com/medspacy/medspacy/blob/master/medspacy/_extensions.py#L205

**Comment by RonWilkinson** [comment]
using {"_": {"section_category": "medications"}} works.   Thanks!
