### ISSUE TITLE
Simple target rules cannot be matched

### ISSUE THREAD

**Issue by bwang482** [medspacy/medspacy#86]
I am testing out the `spacy-v3` branch, on a couple of pretty simple target rules below:

```
target_rules = [
    TargetRule("obsessive-compulsive", "CONDITION", 
              pattern=[
                  {"LOWER": {"IN": ["obsessive-compulsive", "obsessive compulsive"]}}]
                ),
    TargetRule("OCD", "CONDITION", 
              pattern=[
                  {"LOWER": "ocd"}])
]
```

However the first rule doesn't seem to match anything even on an obvious sentence:

> I have obsessive compulsive disorder also known as OCD.

The second rule is able to find the `OCD` instance, I really can't figure out why the first rule doesn't work at all. Shouldn't it just match whatever is in `{"LOWER": {"IN": ["obsessive-compulsive", "obsessive compulsive"]}}` or am I completely missing anything obvious here? Thanks.

**Comment by abchapman93** [comment]
This is something that takes a bit to get used to with spaCy's rule-based matching syntax. I think the issue is that each dict in a pattern needs to correspond to a single _token_, not _span_. So it will match "ocd" because it's a single token, but not "obsessive compulsive". Your rule instead should look something like this:

```python
pattern=[
    {"LOWER": "obsessive"},
    {"LOWER": "-", "OP": "?"},
    {"LOWER": "compulsive"},
]
```

where one dict corresponds to each individual token.

Alternatively, you could also do a simple regex string: `pattern=r"obsessive-?compulsive"`, but that is probably not going to be as efficient, so I recommend doing the list off dicts whenever possible.

Let me know if this helps or if you're still having issues!

**Comment by abchapman93** [comment]
spaCy's documentation has more detailed explanations of this: https://spacy.io/usage/rule-based-matching 

The TargetMatcher wraps up the functionality of the `Matcher` and `PhraseMatcher` classes, as well as normal Python regular expressions.

**Comment by bwang482** [comment]
Brilliant! You're absolutely right, Alec! Thanks!
